export const GET_TEAM_LIST_REQUEST = 'GET_TEAM_LIST_REQUEST'
export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS'
export const GET_TEAM_LIST_FAILURE = 'GET_TEAM_LIST_FAILURE'

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE'

export const GET_TEAM_TOTAL_REQUEST = 'GET_TEAM_TOTAL_REQUEST'
export const GET_TEAM_TOTAL_SUCCESS = 'GET_TEAM_TOTAL_SUCCESS'
export const GET_TEAM_TOTAL_FAILURE = 'GET_TEAM_TOTAL_FAILURE'

export const INC_VIEW_COUNT_REQUEST = 'INC_VIEW_COUNT_REQUEST'
export const INC_VIEW_COUNT_SUCCESS = 'INC_VIEW_COUNT_SUCCESS'
export const INC_VIEW_COUNT_FAILURE = 'INC_VIEW_COUNT_FAILURE'

export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE'

export const ADD_COMMENT_ACTION = 'ADD_COMMENT_ACTION'
