export const GET_TEAM_LIST_REQUEST = 'GET_TEAM_LIST_REQUEST'
export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS'
export const GET_TEAM_LIST_FAILURE = 'GET_TEAM_LIST_FAILURE'

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAILURE = 'GET_TEAM_FAILURE'

export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE'
