//* 비동기 액션 타입
export const LOAD_MY_INFO_REQUEST = 'LOAD_MY_INFO_REQUEST'
export const LOAD_MY_INFO_SUCCESS = 'LOAD_MY_INFO_SUCCESS'
export const LOAD_MY_INFO_FAILURE = 'LOAD_MY_INFO_FAILURE'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

export const GET_USER_TOTAL_REQUEST = 'GET_USER_TOTAL_REQUEST'
export const GET_USER_TOTAL_SUCCESS = 'GET_USER_TOTAL_SUCCESS'
export const GET_USER_TOTAL_FAILURE = 'GET_USER_TOTAL_FAILURE'

export const CHANGE_NICKNAME_REQUEST = 'CHANGE_NICKNAME_REQUEST'
export const CHANGE_NICKNAME_SUCCESS = 'CHANGE_NICKNAME_SUCCESS'
export const CHANGE_NICKNAME_FAILURE = 'CHANGE_NICKNAME_FAILURE'

export const UPLOAD_IMG_REQUEST = 'UPLOAD_IMG_REQUEST'
export const UPLOAD_IMG_SUCCESS = 'UPLOAD_IMG_SUCCESS'
export const UPLOAD_IMG_FAILURE = 'UPLOAD_IMG_FAILURE'

export const DELETE_IMG_REQUEST = 'DELETE_IMG_REQUEST'
export const DELETE_IMG_SUCCESS = 'DELETE_IMG_SUCCESS'
export const DELETE_IMG_FAILURE = 'DELETE_IMG_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

//* 동기 액션 타입
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST'
export const CLEAR_STATE_SUCCESS = 'CLEAR_STATE_SUCCESS'
export const CLEAR_STATE_FAILURE = 'CLEAR_STATE_FAILURE'
